### ISSUE TITLE
Lower half of sentence sometimes cuts off on page breaks

### ISSUE THREAD

**Issue by sdcampbell** [blacklanternsecurity/writehat#8]
There doesn't seem to be anything I can do to reliably reproduce the issue. It seems to depend on the flow of text and where it splits at the bottom of the page. I've tried adding a newline below the affected line but that didn't change anything. I have highlighted the issue in the screenshot below:

![2021-01-14 15_45_58-generatePdf](https://user-images.githubusercontent.com/10532268/104655192-53b8e080-568b-11eb-845d-566021479606.png)

**Comment by sdcampbell** [comment]
It happens in both HTML and PDF view.

**Comment by thejohnbrown** [comment]
You can insert a new line before the paragraph that is cut off and it will push it onto the next page, this should solve the issue for you. I have had this happen with images before where they are inserted at the point of a new page being generated resulting in only half the image being shown.

**Comment by sdcampbell** [comment]
I added a new line before the paragraph that was getting cut off, as you suggested. It did not fix the issue. Next, I tried adding a page break before the affected paragraph. That fixed THAT paragraph, but the result of shifting the text down resulted in the same issue occurring in multiple places throughout the report. Now, instead of having one line cut off, I have multiple lines and an image which is cut off. I could keep adding newlines or page breaks to adjust, but that would require a lot of extra time and trial and error as each change could introduce the same issue in subsequent pages.

**Comment by TheTechromancer** [comment]
This is an unfortunate side-effect of [paged.js](https://gitlab.pagedmedia.org/tools/pagedjs), the library we're using for pagination, water marks, etc.  We've spent a good amount of time troubleshooting this exact issue (and talking with the devs), but so far adding a manual page break is the best solution we've been able to find.

We know it's not ideal.  I'll leave this issue open; if anyone finds a better solution please send a pull request!

Paged.js code: `writehat/static/js/thirdparty/paged.polyfill.js`
Our custom Paged.js overrides: `writehat/static/js/paged-overrides.js`

**Comment by M4RC02U1F4A4** [comment]
Hi, is there any update for this issue? I've tried entering `<br>` or `<p style="page-break-after: always;">&nbsp;</p>` but it doesn't always seem to fix the problem. Am I doing something wrong?
